server:
  port: 8080
  servlet:
    context-path: /community


spring:
  #ThymeleafProperties
  thymeleaf:
    cache: false #关闭缓存

  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123321abc.
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.anyu.community.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

